apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: boutique-image-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "boutique-*"

      commonUpdateSettings:
        updateStrategy: "newest-build"
        allowTags: "regexp:^sha-[a-f0-9]{7,40}$"

      images:
        - alias: adservice
          imageName: ghcr.io/grishma2477/ms/adservice

        - alias: cartservice
          imageName: ghcr.io/grishma2477/ms/cartservice

        - alias: checkoutservice
          imageName: ghcr.io/grishma2477/ms/checkoutservice

        - alias: currencyservice
          imageName: ghcr.io/grishma2477/ms/currencyservice

        - alias: emailservice
          imageName: ghcr.io/grishma2477/ms/emailservice

        - alias: frontend
          imageName: ghcr.io/grishma2477/ms/frontend

        - alias: paymentservice
          imageName: ghcr.io/grishma2477/ms/paymentservice

        - alias: productcatalogservice
          imageName: ghcr.io/grishma2477/ms/productcatalogservice

        - alias: recommendationservice
          imageName: ghcr.io/grishma2477/ms/recommendationservice

        - alias: shippingservice
          imageName: ghcr.io/grishma2477/ms/shippingservice

        - alias: loadgenerator
          imageName: ghcr.io/grishma2477/ms/loadgenerator

